/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUhSQjQwdW45aFo0alFzMVpIalNYT3lZM1gwRFdtcXNTOGMvUmxFK2ZVND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieWNMODdRdEl1VHRTbVk2bVpVWjlUNWtjc052Zmd3UW5nMXJCNFVqbVMxOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVRHN4K1h3MDdPWW5XWXRGUVk1a3VFOC82V1hTT1BjWEFqeXJQL2hPd0VZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzYzZDUVNibEZHYXFHS3VMYStmYVlxWHN2QmNuSDZmczFMamU1U1VVV2hFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVPU1NwNUQ4dE9oWWM3bFRiNmttSE9XSW9ON0IyMFJaRjB6MnlVL1pRM0U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkcxU3NjUTFMb1hhL05KTFl3clRhclAxRm56dG9BcXlLTXlpZEttbG8wVk09In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMEo2VDZESXYrSVVjMnFRRVdFV2graEZwU2FXMlBVYmllbWc5QnhheG1Gcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaWZFTzM5RlBYc2xLSmNwUTIrZGJjVTcwaUt0eVhjYXV0bHQxWVl3RFRtRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkRNdmJVQTVyVEh5bTg5SDJiZ0dXOUptOHNaSUdHTDIxems2eVl1R2dabmFUa2t6eDFxdk9icy9yczIvbklhUWgwdjYyRUpHVmZMY05rR1ZCSi9PL2hRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTMsImFkdlNlY3JldEtleSI6InJtQWI5anl5N0Q3NDJJNzNOTTdYSm9jZkVFRklNSWFMQ2VzQjM5Wk9tUVk9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzQwOTU1NDY2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkE0RDBDQzRDOEJCQjE2NEY5NzdBQ0U4NTg0MjQ5NkZEIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzI0MzI4OTd9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc0MDk1NTQ2NkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI4NjgwRTI1REI5MUEzNERGRDk5NTk5OERDOURCNEEzOSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMyNDMyODk3fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiI3M1pDZGJyMlJSaW91Vm10anBzQU1nIiwicGhvbmVJZCI6ImY2MWE3ODE0LTBjYTItNGUwYS05YzQ0LWQzMjNlMDhkNjZjOCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJsa3BRbjlnSEFUZEdCcjAyQmQ5QlpZazMxRmM9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicTFxTFpKQi94cERGVm9tSDY0ZE1HbVV1NFJJPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjZKUVA3TlBWIiwibWUiOnsiaWQiOiIyNTQ3NDA5NTU0NjY6MzVAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiSmVzc2llIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMU3grZTRERU9xbmk3b0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ5a1ZrUkZFT3ZPUTJUSHRRVklOeVFwVnJ2R2hHSSsxM0Fydk1WS1NXSTN3PSIsImFjY291bnRTaWduYXR1cmUiOiIwblJkREgzRjhQNzBTR0RaV04yd09oMEZKUW5GRzFIUkhuZ0t5N3NHQTlJTVBzTGN1Y0xCWE53bEV5aDB4enF6ZytyMlVwVmZCR2ZXOWliZ3NxZU1BQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiRmVsRWVNQy9ZVkI1cG5qUVRUNTdPMGhqR1oxcUg1VlliMTFUOUg1NlArVVcyelZhNWJCWWpQdEs1b3RzY3k1em1ielpIeTg5Vkx3ZmNJYXBzN25CaHc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3NDA5NTU0NjY6MzVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCY3BGWkVSUkRyemtOa3g3VUZTRGNrS1ZhN3hvUmlQdGR3Szd6RlNrbGlOOCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMjQzMjg4NywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFNUUcifQ==
';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254114018035';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
autolike,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
